# Generated by Django 4.1.7 on 2023-03-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Site name')),
            ],
            options={
                'verbose_name': 'SiteName',
                'verbose_name_plural': 'SiteNames',
            },
        ),
    ]
