# Generated by Django 4.1.7 on 2023-03-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='HomeBg name')),
                ('text', models.TextField(verbose_name='HomeBg text')),
                ('img', models.ImageField(upload_to='images', verbose_name='HomeBg image')),
            ],
            options={
                'verbose_name': 'HomeBg',
                'verbose_name_plural': 'HomeBgs',
            },
        ),
    ]
