# Generated by Django 4.1.7 on 2023-03-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_homebg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Info name')),
                ('img', models.ImageField(upload_to='images', verbose_name='Info image')),
                ('text1', models.TextField(verbose_name='Info text1')),
                ('text2', models.TextField(verbose_name='Info text2')),
            ],
            options={
                'verbose_name': 'Info',
                'verbose_name_plural': 'Infos',
            },
        ),
    ]
