# Generated by Django 4.1.7 on 2023-03-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Product name')),
                ('text', models.TextField(verbose_name='Product text')),
                ('img1', models.ImageField(upload_to='images', verbose_name='Product image1')),
                ('img2', models.ImageField(upload_to='images', verbose_name='Product image2')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
