# Generated by Django 4.1.7 on 2023-03-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='About Client name')),
                ('text', models.TextField(verbose_name='About Client text')),
            ],
            options={
                'verbose_name': 'AboutClient',
                'verbose_name_plural': 'AboutClients',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(verbose_name='Client link')),
                ('img', models.ImageField(upload_to='images', verbose_name='Client image')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
    ]
